openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /study-materials:
    get:
      summary: Returns a list of study-materials.
      description: List from specifying discipline.
      parameters:
        - name: discipline_name
          in: path
          required: true
          description: specifying discipline.
          schema:
            type: string
            format: int64
            minimum: 1
      responses:
        "200": # status code
          description: A JSON array of study materials.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      summary: Upload study-materials.
      description: Upload one or more study-materials.
      # TODO need add params
      # discipline_name : string
      responses:
        "200": # status code
          description:

    patch:
      summary: Rename study-materials.
      description: Rename study-materials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
            type: object
            properties:
              old_name:
                type: string
              new_name:
                type: string
              discipline_name:
                type: string
      responses:
        "200": # status code
          description:

    delete:
      summary: Delete study-materials.
      description: Delete study-materials.
      requestBody:
        required: true
        content:
          application/json:
            schema:
            type: object
            properties:
              name:
                type: string
              discipline_name:
                type: string
      responses:
        "200": # status code
          description:

  /disciplines:
    get:
      summary: Returns a list of disciplines.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of discipline names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      summary: Create discipline.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200": # status code
          description:

    put:
      summary: Rename discipline.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                old_name:
                  type: string
                new_name:
                  type: string
      responses:
        "200": # status code
          description:

    delete:
      summary: Delete discipline.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "200": # status code
          description:

  /news:
    get:
      summary: Returns a list of news.
      description: Returns a list of news.
      responses:
        "200": # status code
          description: A JSON array of news.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    content:
                      type: string

    post:
      summary: Create one news.
      description: Create one news.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
      responses:
        "200": # status code
          description: 

    put:
      summary: Update one news.
      description: Update one news.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                content:
                  type: string
      responses:
        "200": # status code
          description:

    delete:
      summary: Delete one news.
      description: Delete one news.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        "200": # status code
          description:

  /publications:
    get:
      summary: Returns a list of publications.
      description: Returns a list of publications.
      responses:
        "200": # status code
          description: A JSON array of publications.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      summary: Create publication.
      description: Create publication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: number
                content:
                  type: string
      responses:
        "200": # status code
          description: 

    put:
      summary: Update publication.
      description: Update publication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                year:
                  type: number
                content:
                  type: string
      responses:
        "200": # status code
          description:

    delete:
      summary: Delete publication.
      description: Delete publication.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
      responses:
        "200": # status code
          description:

  /student-work:
    get:
      summary: Returns a list of student work.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    post:
      summary: Create student work.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    put:
      summary: Update student work.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

    delete:
      summary: Delete student work.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
